### ISSUE TITLE
bug open tiles in floating windows

### ISSUE THREAD

**Issue by Djfe** [zst123/XHaloFloatingWindow#21]
If I activate the open tile in floating window setting the tiles won't open their destination at all (for example the settings app doesn't open at all if I click the settings tile)

**Comment by zst123** [comment]
Hi, 

Do you receive an error that shows something like [this](http://tapatalk.com/tapatalk_image.php?img=aHR0cDovL2ltZy50YXBhdGFsay5jb20vZC8xNC8wNS8yMy9vcmlnaW5hbC9oYXRlemU0YS5qcGc%3D) OR [this](http://tapatalk.com/tapatalk_image.php?img=aHR0cDovL2ltZy50YXBhdGFsay5jb20vZC8xNC8wNS8xOC9vcmlnaW5hbC9lbXVneWh1cC5qcGc%3D)?

 If so, it will be fixed in the next version coming soon. Meanwhile, you can try the fix at the [bottom of this page](http://forum.xda-developers.com/showpost.php?p=52672373&postcount=2440)

If it is not the error shown above, could you send me your Xposed Installer Log?

**Comment by Djfe** [comment]
Actually my ROM doesn't show any error at all, and now nothing works (the whole floating window doesn't appear if I try to open soemthing through the task manager) 

the log shows a lot of errors in conjunction with halo though

thx for the .apk -> why does the filename say 2.33 but it is 2.32?

the new .apk has fixed it, thx
-> now new entries in the log file while using xhalofloatingwindow
looking forward to the next version ;)

log file:

```
-----------------
25.05.2014 01:09:14 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'carbon_anzu-userdebug 4.4.2 KVT49L 5056f161c7 test-keys' with fingerprint 'SEMC/LT18i_1254-2184/LT18i:4.0.4/4.1.B.0.587/tL1_3w:user/release-keys'
Loading modules from /data/app/ccc71.at-1.apk
  Loading class ccc71.at.xposed.at_xposed_enabled
  Loading class ccc71.at.xposed.at_remove_battery_icon
  Loading class ccc71.at.xposed.at_remove_low_battery_warning
  Loading class ccc71.at.xposed.at_apps
  Loading class ccc71.at.xposed.at_fix_mnt_asec
Loading modules from /data/app/com.zst.xposed.halo.floatingwindow-1.apk
  Loading class com.zst.xposed.halo.floatingwindow.MainXposed
Hooking: android from /data/data/ccc71.at/xposed/at_crystal_apps
Hooking: android from /data/data/ccc71.at/xposed/at_sd_apps
java.lang.IllegalAccessException: access to field not allowed
    at java.lang.reflect.Field.getField(Native Method)
    at java.lang.reflect.Field.get(Field.java:266)
    at com.zst.xposed.halo.floatingwindow.hooks.NotificationShadeHook$4.afterHookedMethod(NotificationShadeHook.java:364)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
    at com.android.systemui.quicksettings.QuickSettingsTile.startSettingsActivity(Native Method)
    at com.android.systemui.quicksettings.QuickSettingsTile.startSettingsActivity(QuickSettingsTile.java:168)
    at com.android.systemui.quicksettings.QuickSettingsTile.startSettingsActivity(QuickSettingsTile.java:164)
    at com.android.systemui.quicksettings.PreferencesTile$1.onClick(PreferencesTile.java:20)
    at com.android.systemui.quicksettings.QuickSettingsTile.onClick(QuickSettingsTile.java:186)
    at android.view.View.performClick(View.java:4438)
    at android.view.View$PerformClick.run(View.java:18439)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5149)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:807)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.drawableToBitmap(ActionBarColorHook.java:247)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.getMainColorFromActionBarDrawable(ActionBarColorHook.java:232)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.access$0(ActionBarColorHook.java:222)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook$1.beforeHookedMethod(ActionBarColorHook.java:79)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.internal.app.ActionBarImpl.setBackgroundDrawable(Native Method)
    at ccc71.at.activities.helpers.m.a(SourceFile:313)
    at ccc71.at.prefs.at_settings.onCreate(SourceFile:7099)
    at android.app.Activity.performCreate(Activity.java:5241)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
    at android.app.ActivityThread.access$800(ActivityThread.java:145)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5149)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:807)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.drawableToBitmap(ActionBarColorHook.java:247)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.getMainColorFromActionBarDrawable(ActionBarColorHook.java:232)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.access$0(ActionBarColorHook.java:222)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook$1.beforeHookedMethod(ActionBarColorHook.java:79)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.internal.app.ActionBarImpl.setBackgroundDrawable(Native Method)
    at android.support.v7.app.o.a(SourceFile:189)
    at android.support.v7.app.p.a(SourceFile:20)
    at ccc71.at.activities.helpers.m.a(SourceFile:307)
    at ccc71.at.activities.helpers.at_activity.onCreate(SourceFile:110)
    at ccc71.at.activities.tm.at_monitor.onCreate(SourceFile:1028)
    at android.app.Activity.performCreate(Activity.java:5241)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
    at android.app.ActivityThread.access$800(ActivityThread.java:145)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5149)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:807)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.drawableToBitmap(ActionBarColorHook.java:247)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.getMainColorFromActionBarDrawable(ActionBarColorHook.java:232)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.access$0(ActionBarColorHook.java:222)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook$1.beforeHookedMethod(ActionBarColorHook.java:79)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.internal.app.ActionBarImpl.setBackgroundDrawable(Native Method)
    at android.support.v7.app.o.a(SourceFile:189)
    at android.support.v7.app.p.a(SourceFile:20)
    at ccc71.at.activities.helpers.m.a(SourceFile:307)
    at ccc71.at.activities.helpers.at_activity.onCreate(SourceFile:110)
    at ccc71.at.activities.tm.at_monitor.onCreate(SourceFile:1028)
    at android.app.Activity.performCreate(Activity.java:5241)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
    at android.app.ActivityThread.access$800(ActivityThread.java:145)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5149)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:807)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.drawableToBitmap(ActionBarColorHook.java:247)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.getMainColorFromActionBarDrawable(ActionBarColorHook.java:232)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.access$0(ActionBarColorHook.java:222)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook$1.beforeHookedMethod(ActionBarColorHook.java:79)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.internal.app.ActionBarImpl.setBackgroundDrawable(Native Method)
    at android.support.v7.app.o.a(SourceFile:189)
    at android.support.v7.app.p.a(SourceFile:20)
    at ccc71.at.activities.helpers.m.a(SourceFile:307)
    at ccc71.at.activities.helpers.at_themed_fragment_activity.onCreate(SourceFile:46)
    at ccc71.at.activities.helpers.at_tab_fragment_activity.onCreate(SourceFile:75)
    at ccc71.at.activities.tweaks.at_tweaks.onCreate(SourceFile:54)
    at android.app.Activity.performCreate(Activity.java:5241)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
    at android.app.ActivityThread.access$800(ActivityThread.java:145)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5149)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:807)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.drawableToBitmap(ActionBarColorHook.java:247)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.getMainColorFromActionBarDrawable(ActionBarColorHook.java:232)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.access$0(ActionBarColorHook.java:222)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook$1.beforeHookedMethod(ActionBarColorHook.java:79)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.internal.app.ActionBarImpl.setBackgroundDrawable(Native Method)
    at android.support.v7.app.o.a(SourceFile:189)
    at android.support.v7.app.p.a(SourceFile:20)
    at ccc71.at.activities.helpers.m.a(SourceFile:307)
    at ccc71.at.activities.helpers.at_themed_fragment_activity.onCreate(SourceFile:46)
    at ccc71.at.activities.helpers.at_tab_fragment_activity.onCreate(SourceFile:75)
    at ccc71.at.activities.apps.at_apps.onCreate(SourceFile:68)
    at android.app.Activity.performCreate(Activity.java:5241)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)
    at android.app.ActivityThread.access$800(ActivityThread.java:145)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5149)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
XHaloFloatingWindow(SDK: 19) - RecentAppsHook / onMenuItemClick (3000)
java.lang.IllegalAccessException: access to field not allowed
    at java.lang.reflect.Field.getField(Native Method)
    at java.lang.reflect.Field.get(Field.java:266)
    at com.zst.xposed.halo.floatingwindow.hooks.RecentAppsHook$1$1.onMenuItemClick(RecentAppsHook.java:101)
    at android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:201)
    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
    at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:177)
    at android.widget.AdapterView.performItemClick(AdapterView.java:298)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1139)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3048)
    at android.widget.AbsListView$4.run(AbsListView.java:3790)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5149)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
XHaloFloatingWindow(SDK: 19) - RecentAppsHook / onMenuItemClick (3000)
java.lang.IllegalAccessException: access to field not allowed
    at java.lang.reflect.Field.getField(Native Method)
    at java.lang.reflect.Field.get(Field.java:266)
    at com.zst.xposed.halo.floatingwindow.hooks.RecentAppsHook$1$1.onMenuItemClick(RecentAppsHook.java:101)
    at android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:201)
    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
    at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:177)
    at android.widget.AdapterView.performItemClick(AdapterView.java:298)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1139)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3048)
    at android.widget.AbsListView$4.run(AbsListView.java:3790)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5149)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
XHaloFloatingWindow(SDK: 19) - RecentAppsHook / onMenuItemClick (3000)
java.lang.IllegalAccessException: access to field not allowed
    at java.lang.reflect.Field.getField(Native Method)
    at java.lang.reflect.Field.get(Field.java:266)
    at com.zst.xposed.halo.floatingwindow.hooks.RecentAppsHook$1$1.onMenuItemClick(RecentAppsHook.java:101)
    at android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:201)
    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
    at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:177)
    at android.widget.AdapterView.performItemClick(AdapterView.java:298)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1139)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3048)
    at android.widget.AbsListView$4.run(AbsListView.java:3790)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5149)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
-----------------
25.05.2014 09:51:06 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'carbon_anzu-userdebug 4.4.2 KVT49L 5056f161c7 test-keys' with fingerprint 'SEMC/LT18i_1254-2184/LT18i:4.0.4/4.1.B.0.587/tL1_3w:user/release-keys'
Loading modules from /data/app/ccc71.at-1.apk
  Loading class ccc71.at.xposed.at_xposed_enabled
  Loading class ccc71.at.xposed.at_remove_battery_icon
  Loading class ccc71.at.xposed.at_remove_low_battery_warning
  Loading class ccc71.at.xposed.at_apps
  Loading class ccc71.at.xposed.at_fix_mnt_asec
Loading modules from /data/app/com.zst.xposed.halo.floatingwindow-1.apk
  Loading class com.zst.xposed.halo.floatingwindow.MainXposed
Hooking: android from /data/data/ccc71.at/xposed/at_crystal_apps
Hooking: android from /data/data/ccc71.at/xposed/at_sd_apps
```
