### ISSUE TITLE
Xposed Log nullpointerexception

### ISSUE THREAD

**Issue by Djfe** [zst123/XHaloFloatingWindow#24]
Maybe you find out what went wrong here. I don't know when this happened, just wanted to post it so that you can fix it ;)

```
-----------------
15.07.2014 09:18:37 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'carbon_anzu-userdebug 4.4.4 KTU84P f0982e5a75 test-keys' with fingerprint 'SEMC/LT18i_1254-2184/LT18i:4.0.4/4.1.B.0.587/tL1_3w:user/release-keys'
Loading modules from /data/app/hk.valenta.completeactionplus-1.apk
  Loading class hk.valenta.completeactionplus.XCompleteActionPlus
Loading modules from /data/app/com.ugglynoodle.allnotificationsexpanded-1.apk
  Loading class com.ugglynoodle.allnotificationsexpanded.AllNotificationsExpanded
Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-1.apk
  Loading class de.robv.android.xposed.mods.appsettings.XposedMod
Loading modules from /data/app/com.germainz.crappalinks-1.apk
  Loading class com.germainz.crappalinks.CrappaLinks
Loading modules from /data/app/com.mohammadag.shortcutinappinfo-1.apk
  Loading class com.mohammadag.shortcutinappinfo.XposedMod
Loading modules from /mnt/asec/ccc71.at-1/pkg.apk
  File does not exist
Loading modules from /data/app/pk.qwerty12.playstorelinkinappinfo-1.apk
  Loading class pk.qwerty12.playstorelinkinappinfo.PlayStoreLinkInAppInfo
Loading modules from /data/app/com.zst.xposed.halo.floatingwindow-1.apk
  Loading class com.zst.xposed.halo.floatingwindow.MainXposed
-----------------
15.07.2014 10:09:46 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'carbon_anzu-userdebug 4.4.4 KTU84P f0982e5a75 test-keys' with fingerprint 'SEMC/LT18i_1254-2184/LT18i:4.0.4/4.1.B.0.587/tL1_3w:user/release-keys'
Loading modules from /data/app/hk.valenta.completeactionplus-1.apk
  Loading class hk.valenta.completeactionplus.XCompleteActionPlus
Loading modules from /data/app/com.ugglynoodle.allnotificationsexpanded-1.apk
  Loading class com.ugglynoodle.allnotificationsexpanded.AllNotificationsExpanded
Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-1.apk
  Loading class de.robv.android.xposed.mods.appsettings.XposedMod
Loading modules from /data/app/com.germainz.crappalinks-1.apk
  Loading class com.germainz.crappalinks.CrappaLinks
Loading modules from /data/app/com.mohammadag.shortcutinappinfo-1.apk
  Loading class com.mohammadag.shortcutinappinfo.XposedMod
Loading modules from /mnt/asec/ccc71.at-1/pkg.apk
  File does not exist
Loading modules from /data/app/pk.qwerty12.playstorelinkinappinfo-1.apk
  Loading class pk.qwerty12.playstorelinkinappinfo.PlayStoreLinkInAppInfo
Loading modules from /data/app/com.zst.xposed.halo.floatingwindow-1.apk
  Loading class com.zst.xposed.halo.floatingwindow.MainXposed
java.lang.NullPointerException
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.getMainColorFromActionBarDrawable(ActionBarColorHook.java:235)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.access$0(ActionBarColorHook.java:230)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook$1.beforeHookedMethod(ActionBarColorHook.java:84)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.internal.app.ActionBarImpl.setBackgroundDrawable(Native Method)
    at com.maxmpz.audioplayer.PlayerUIActivity.onCreate(":228)
    at android.app.Activity.performCreate(Activity.java:5322)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2182)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2277)
    at android.app.ActivityThread.access$800(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5147)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NullPointerException
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.getMainColorFromActionBarDrawable(ActionBarColorHook.java:235)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.changeColorFromActionBarObject(ActionBarColorHook.java:145)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.access$5(ActionBarColorHook.java:130)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook$3.afterHookedMethod(ActionBarColorHook.java:108)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
    at com.android.internal.app.ActionBarImpl.show(Native Method)
    at com.maxmpz.audioplayer.BaseThemeableActivity.l11l(":543)
    at com.maxmpz.audioplayer.PlayerUIActivity.l11l(":657)
    at com.maxmpz.audioplayer.BaseThemeableActivity.onClick(":807)
    at com.maxmpz.audioplayer.PlayerUIActivity.onClick(":1200)
    at android.view.View.performClick(View.java:4438)
    at android.view.View$PerformClick.run(View.java:18439)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5147)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
java.lang.NullPointerException
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.getMainColorFromActionBarDrawable(ActionBarColorHook.java:235)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.changeColorFromActionBarObject(ActionBarColorHook.java:145)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook.access$5(ActionBarColorHook.java:130)
    at com.zst.xposed.halo.floatingwindow.hooks.ActionBarColorHook$3.afterHookedMethod(ActionBarColorHook.java:108)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
    at com.android.internal.app.ActionBarImpl.show(Native Method)
    at com.maxmpz.audioplayer.BaseThemeableActivity.l11l(":543)
    at com.maxmpz.audioplayer.PlayerUIActivity.l11l(":657)
    at com.maxmpz.audioplayer.BaseThemeableActivity.onClick(":807)
    at com.maxmpz.audioplayer.PlayerUIActivity.onClick(":1200)
    at android.view.View.performClick(View.java:4438)
    at android.view.View$PerformClick.run(View.java:18439)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5147)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
-----------------
15.07.2014 12:12:36 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'carbon_anzu-userdebug 4.4.4 KTU84P f0982e5a75 test-keys' with fingerprint 'SEMC/LT18i_1254-2184/LT18i:4.0.4/4.1.B.0.587/tL1_3w:user/release-keys'
Loading modules from /data/app/hk.valenta.completeactionplus-1.apk
  Loading class hk.valenta.completeactionplus.XCompleteActionPlus
Loading modules from /data/app/com.ugglynoodle.allnotificationsexpanded-1.apk
  Loading class com.ugglynoodle.allnotificationsexpanded.AllNotificationsExpanded
Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-1.apk
  Loading class de.robv.android.xposed.mods.appsettings.XposedMod
Loading modules from /data/app/com.germainz.crappalinks-1.apk
  Loading class com.germainz.crappalinks.CrappaLinks
Loading modules from /data/app/com.mohammadag.shortcutinappinfo-1.apk
  Loading class com.mohammadag.shortcutinappinfo.XposedMod
Loading modules from /mnt/asec/ccc71.at-1/pkg.apk
  File does not exist
Loading modules from /data/app/pk.qwerty12.playstorelinkinappinfo-1.apk
  Loading class pk.qwerty12.playstorelinkinappinfo.PlayStoreLinkInAppInfo
Loading modules from /data/app/com.zst.xposed.halo.floatingwindow-1.apk
  Loading class com.zst.xposed.halo.floatingwindow.MainXposed
```

**Comment by zst123** [comment]
Hi Djfe, 

Thanks for the log! I have thought of a fix already. I will fix it in code once I find time

Regards,
zst123

**Comment by Djfe** [comment]
ok thank you in advance ;)

**Comment by zst123** [comment]
The fix is merged here
https://github.com/zst123/XHaloFloatingWindow/commit/bf84858b66da4a6b11e1636556fa4805477ef7c1
